spring.application.name=fitg-ai-client

spring.ai.ollama.chat.model=gemma4:e4b-mlx

# Enable the folling line to gain insignt into the AI conversation
# logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug